name: Version auto-merge
on:
  pull_request:
    types: [opened, edited, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  version-update:
    runs-on: ubuntu-latest
    #if: ${{ github.event.pull_request.head.ref == 'update-version' }}
    steps:
      - run: |
          echo "${{ github.actor }}"
          echo "${{ github.event.pull_request.head.ref }}"
      - name: Merge new version
        run: gh pr merge -ds --auto $PR_URL
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
